local M = {}

local function safeRequire(mod)
    local ok, res = pcall(require, mod)
    if ok then return res end
    return nil
end

function M.loadForClass(classShort)
    if type(classShort) ~= 'string' or classShort == '' then return {} end
    classShort = classShort:upper()
    local list = {}

    -- AAs (generated by aa_discovery)
    do
        local mod = string.format('data.classes.%s', classShort)
        local res = safeRequire(mod)
        local abilities = (type(res) == 'table') and (res.abilities or res) or nil
        if type(abilities) == 'table' then
            for _, def in ipairs(abilities) do
                table.insert(list, def)
            end
        end
    end

    -- Disciplines (hand-curated per class)
    do
        local mod = string.format('data.disciplines.%s', classShort)
        local res = safeRequire(mod)
        local discs = (type(res) == 'table') and (res.disciplines or res) or nil
        if type(discs) == 'table' then
            for _, def in ipairs(discs) do
                table.insert(list, def)
            end
        end
    end

    return list
end

return M
