$ErrorActionPreference = 'Stop'

function Get-PlainTextFromHtml([string]$html) {
    if ([string]::IsNullOrWhiteSpace($html)) { return '' }
    $s = $html -replace '(?i)<br\s*/?>', "`n"
    $s = [System.Net.WebUtility]::HtmlDecode($s)
    $s = $s -replace '<[^>]+>', ''
    $s = $s -replace "`r", ''

    $lines = @()
    foreach ($line in ($s -split "`n")) {
        $t = ([regex]::Replace($line, '\s+', ' ')).Trim()
        if ($t) { $lines += $t }
    }
    return ($lines -join "`n")
}

function Escape-LuaSingleQuoted([string]$s) {
    if ($null -eq $s) { return '' }
    $s = $s -replace '\\', '\\\\'
    $s = $s -replace "'", "\'"
    $s = $s -replace "`r", ''
    $s = $s -replace "`n", "\\n"
    return $s
}

function Get-TimerSpells([int]$timer) {
    $timerName = ('Timer_{0:d2}' -f $timer)
    $resp = Invoke-WebRequest `
        -Method Post `
        -Uri 'https://www.raidloot.com/class/berserker/spells' `
        -ContentType 'application/x-www-form-urlencoded; charset=UTF-8' `
        -Body @{ name = $timerName; level = '130' }

    $rows = [regex]::Matches($resp.Content, '<tr id="spell\d+"[\s\S]*?</tr>')
    $out = @()
    foreach ($row in $rows) {
        $tds = [regex]::Matches($row.Value, '<td[^>]*>([\s\S]*?)</td>')
        if ($tds.Count -lt 10) { continue }

        $spellName = (Get-PlainTextFromHtml($tds[1].Groups[1].Value)).Trim()
        if ([string]::IsNullOrWhiteSpace($spellName)) { continue }

        $lvlText = Get-PlainTextFromHtml($tds[2].Groups[1].Value)
        $lvl = 0
        [void][int]::TryParse(($lvlText -replace '\D', ''), [ref]$lvl)

        $desc = Get-PlainTextFromHtml($tds[9].Groups[1].Value)

        $out += [pscustomobject]@{
            name  = $spellName
            level = $lvl
            timer = $timer
            desc  = $desc
        }
    }
    return $out
}

$all = @()
for ($t = 1; $t -le 22; $t++) {
    Write-Host ("[SideKick] Fetching Timer_{0:d2}..." -f $t) -ForegroundColor Cyan
    $all += Get-TimerSpells $t
}

# Filter obvious non-discipline artifacts; SideKick still filters to trained/known discs at runtime.
$items = $all | Where-Object { $_.level -gt 0 -and $_.name -notmatch '(Effect|Recourse)$' }

# Dedupe by name; keep highest level.
$dedup = $items | Group-Object name | ForEach-Object {
    $_.Group | Sort-Object @{ Expression = 'level'; Descending = $true }, @{ Expression = 'timer'; Ascending = $true } | Select-Object -First 1
}

# Sort: timer asc, level desc, name asc.
$sorted = $dedup | Sort-Object @{ Expression = 'timer'; Ascending = $true }, @{ Expression = 'level'; Descending = $true }, @{ Expression = 'name'; Ascending = $true }

$maxDesc = 320
$lines = foreach ($d in $sorted) {
    $desc = $d.desc
    if ($null -eq $desc) { $desc = '' }
    if ($desc.Length -gt $maxDesc) { $desc = $desc.Substring(0, $maxDesc).TrimEnd() + '...' }

    $n = Escape-LuaSingleQuoted $d.name
    $ds = Escape-LuaSingleQuoted $desc
    "    { name = '$n', level = $($d.level), timer = $($d.timer), desc = '$ds' },"
}

$outPath = Join-Path $PSScriptRoot '..\\data\\disciplines\\BER_data.lua'
$header = @(
    '-- Auto-generated by tools/sync_ber_disciplines.ps1'
    '-- Source: https://www.raidloot.com/class/berserker?level=130#/spell/Timer_01 .. Timer_22'
    'return {'
)
$footer = @('}', '')

($header + $lines + $footer) | Set-Content -LiteralPath $outPath -Encoding UTF8

Write-Host ("[SideKick] Wrote {0} entries to {1}" -f $lines.Count, $outPath) -ForegroundColor Green
